-- ArabFunny / Gen Alpha Library Effect
-- Nonsensical Video Generator
-- Generated custom Workshop effect
--
-- Concept:
--   Randomly injects Gen Alpha / ArabFunny-style media from
--   custom NVG libraries, with optional speed, repetition,
--   reverse, pitch, and chaos-style transformations.
--
-- Suggested addon filename:
--   arabfunny_gen_alpha.lua

local addon = {}

function Query()
    return {
        ["name"] = "ArabFunny / Gen Alpha Library",

        ["description"] =
            "Randomly mixes ArabFunny and Gen Alpha media " ..
            "into the current NVG render with chaotic meme-style edits.",

        ["settings"] = {
            {
                ["name"] = "Chance Roll",
                ["value"] = 50,
                ["type"] = "number"
            },

            {
                ["name"] = "Chaos Level",
                ["value"] = 65,
                ["type"] = "number"
            },

            {
                ["name"] = "Repeat Chance",
                ["value"] = 25,
                ["type"] = "number"
            },

            {
                ["name"] = "Reverse Chance",
                ["value"] = 20,
                ["type"] = "number"
            },

            {
                ["name"] = "Speed Chaos",
                ["value"] = 35,
                ["type"] = "number"
            }
        },

        -- These are custom/community libraries.
        -- Rename them to match the actual library names
        -- installed in your NVG setup.
        ["libraries"] = {
            "ArabFunny",
            "Gen Alpha"
        }
    }
end


------------------------------------------------------------
-- Utility
------------------------------------------------------------

local function randomChance(percent)
    return math.random(1, 100) <= percent
end


local function randomSpeed()
    local speeds = {
        0.50,
        0.67,
        0.80,
        1.00,
        1.25,
        1.50,
        1.75,
        2.00,
        2.50
    }

    return speeds[math.random(1, #speeds)]
end


------------------------------------------------------------
-- Effect
------------------------------------------------------------

function Effect(job)
    local chance = tonumber(job.settings["Chance Roll"]) or 50
    local chaos = tonumber(job.settings["Chaos Level"]) or 65
    local repeatChance =
        tonumber(job.settings["Repeat Chance"]) or 25
    local reverseChance =
        tonumber(job.settings["Reverse Chance"]) or 20
    local speedChaos =
        tonumber(job.settings["Speed Chaos"]) or 35

    -- Main activation roll
    if not randomChance(chance) then
        return job
    end

    --------------------------------------------------------
    -- Random ArabFunny / Gen Alpha material
    --------------------------------------------------------

    -- The exact library API can vary between NVG versions.
    -- This section is intentionally kept as a clear integration
    -- point for the library functions exposed by your template.
    --
    -- Example library targets:
    --
    --   ArabFunny
    --   Gen Alpha
    --
    -- Recommended media:
    --   short meme clips
    --   reaction clips
    --   Arabic meme audio
    --   Gen Alpha sound effects
    --   short vertical/video snippets
    --   absurd transitions
    --
    -- Replace the following placeholder call with the
    -- corresponding library-selection function from the
    -- template generated by your NVG installation.

    if functions ~= nil then

        ----------------------------------------------------
        -- Random chaos behavior
        ----------------------------------------------------

        if randomChance(chaos) then

            -- Speed manipulation
            if randomChance(speedChaos) then
                local speed = randomSpeed()

                if functions.setSpeed ~= nil then
                    functions.setSpeed(speed)
                end
            end


            -- Reverse
            if randomChance(reverseChance) then
                if functions.reverse ~= nil then
                    functions.reverse()
                end
            end


            -- Repetition / stutter
            if randomChance(repeatChance) then
                if functions.repeatClip ~= nil then
                    local repeats = math.random(2, 5)
                    functions.repeatClip(repeats)
                end
            end

        end

    end

    return job
end


------------------------------------------------------------
-- Metadata
------------------------------------------------------------

function GetName()
    return "ArabFunny / Gen Alpha Library"
end


function GetDescription()
    return
        "Chaotic ArabFunny and Gen Alpha meme-library effect " ..
        "with randomized speed, reverse and repetition."
end


return addon
